begin;

create extension if not exists pgcrypto with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email varchar(255) unique not null,
  nickname varchar(100) not null,
  profile_image varchar(500),
  approval_status varchar(30) not null default 'approved',
  approved_at timestamptz,
  requested_at timestamptz not null default now(),
  profile_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_agreements (
  user_id uuid primary key references public.users(user_id) on delete cascade,
  terms_agreed_at timestamptz not null,
  privacy_agreed_at timestamptz not null,
  terms_version varchar(30) not null,
  privacy_version varchar(30) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  preference_id bigint generated by default as identity primary key,
  user_id uuid unique not null references public.users(user_id) on delete cascade,
  badge varchar(100),
  mbti_type varchar(4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.travel_mbti_results (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references public.users(user_id) on delete cascade,
  mbti_type varchar(4) not null,
  ei_score smallint not null,
  sn_score smallint not null,
  tf_score smallint not null,
  jp_score smallint not null,
  raw_answers jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.destinations (
  destination_id bigint generated by default as identity primary key,
  province varchar(100) not null,
  city varchar(100),
  destination_name varchar(255) not null,
  description text,
  category varchar(100),
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  image_url varchar(1000),
  tour_content_id varchar(50),
  content_type_id integer,
  address varchar(500),
  category_code1 varchar(20),
  category_code2 varchar(20),
  category_code3 varchar(20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint destinations_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint destinations_longitude_check
    check (longitude is null or longitude between -180 and 180)
);

create unique index if not exists destinations_tour_content_id_idx
  on public.destinations(tour_content_id)
  where tour_content_id is not null;
create index if not exists destinations_region_idx
  on public.destinations(province, city);
create index if not exists destinations_category_idx
  on public.destinations(category);

create table if not exists public.destination_keywords (
  destination_keyword_id bigint generated by default as identity primary key,
  destination_id bigint not null references public.destinations(destination_id) on delete cascade,
  keyword varchar(50) not null,
  source varchar(20) not null default 'RULE',
  confidence numeric(4, 3) not null default 1,
  rule_version varchar(50),
  created_at timestamptz not null default now(),
  constraint destination_keywords_unique unique (destination_id, keyword),
  constraint destination_keywords_source_check
    check (source in ('TOUR_API', 'RULE', 'AI', 'ADMIN')),
  constraint destination_keywords_confidence_check
    check (confidence between 0 and 1)
);

create table if not exists public.destination_mbti_scores (
  destination_mbti_score_id bigint generated by default as identity primary key,
  destination_id bigint not null references public.destinations(destination_id) on delete cascade,
  mbti_type varchar(4) not null,
  score numeric(5, 2) not null,
  reason text,
  source varchar(20) not null default 'RULE',
  rule_version varchar(50) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint destination_mbti_scores_unique unique (destination_id, mbti_type),
  constraint destination_mbti_scores_score_check check (score between 0 and 100),
  constraint destination_mbti_scores_source_check check (source in ('RULE', 'AI', 'ADMIN'))
);

create table if not exists public.user_bookmarks (
  bookmark_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  destination_id bigint not null references public.destinations(destination_id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint user_bookmarks_unique unique (user_id, destination_id)
);

create table if not exists public.trips (
  trip_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  title varchar(255) not null,
  start_date date,
  end_date date,
  memo text,
  status varchar(30) not null default 'planning',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trips_date_range_check
    check (start_date is null or end_date is null or end_date >= start_date),
  constraint trips_status_check
    check (status in ('planning', 'in_progress', 'completed', 'cancelled'))
);

create table if not exists public.trip_plans (
  plan_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  title varchar(100) not null,
  mbti_type varchar(4),
  region varchar(50),
  total_days integer not null default 1,
  keyword varchar(100),
  ai_summary text,
  status varchar(30) not null default 'planning',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_plans_total_days_check check (total_days between 1 and 7),
  constraint trip_plans_status_check check (status in ('planning', 'in_progress', 'completed'))
);

create table if not exists public.trip_plan_items (
  item_id bigint generated by default as identity primary key,
  plan_id bigint not null references public.trip_plans(plan_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  destination_id bigint not null references public.destinations(destination_id) on delete cascade,
  day_number integer not null,
  order_index integer not null,
  memo text,
  created_at timestamptz not null default now(),
  constraint trip_plan_items_day_number_check check (day_number >= 1),
  constraint trip_plan_items_order_index_check check (order_index >= 1)
);

create table if not exists public.community_posts (
  post_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  nickname varchar(100),
  title varchar(255) not null,
  summary text,
  tags text,
  location varchar(100),
  category varchar(100),
  type varchar(50),
  like_count integer not null default 0,
  comment_count integer not null default 0,
  image_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_comments (
  comment_id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(post_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  nickname varchar(100),
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.community_likes (
  like_id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(post_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint community_likes_unique unique (post_id, user_id)
);

create table if not exists public.community_comment_likes (
  comment_id bigint not null references public.community_comments(comment_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

create table if not exists public.community_shares (
  share_id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(post_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  shared_url text,
  created_at timestamptz not null default now()
);

alter table public.user_preferences
  drop constraint if exists user_preferences_mbti_type_check;
alter table public.user_preferences
  add constraint user_preferences_mbti_type_check
  check (
    mbti_type is null or mbti_type in (
      'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
      'ISTP', 'ISFP', 'INFP', 'INTP',
      'ESTP', 'ESFP', 'ENFP', 'ENTP',
      'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ'
    )
  );

alter table public.travel_mbti_results
  drop constraint if exists travel_mbti_results_mbti_type_check;
alter table public.travel_mbti_results
  add constraint travel_mbti_results_mbti_type_check
  check (
    mbti_type in (
      'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
      'ISTP', 'ISFP', 'INFP', 'INTP',
      'ESTP', 'ESFP', 'ENFP', 'ENTP',
      'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ'
    )
  );

alter table public.destination_mbti_scores
  drop constraint if exists destination_mbti_scores_mbti_type_check;
alter table public.destination_mbti_scores
  add constraint destination_mbti_scores_mbti_type_check
  check (
    mbti_type in (
      'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
      'ISTP', 'ISFP', 'INFP', 'INTP',
      'ESTP', 'ESFP', 'ENFP', 'ENTP',
      'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ'
    )
  );

create index if not exists user_agreements_user_id_idx
  on public.user_agreements(user_id);
create index if not exists user_preferences_user_id_idx
  on public.user_preferences(user_id);
create index if not exists travel_mbti_results_user_id_idx
  on public.travel_mbti_results(user_id);
create index if not exists destination_keywords_destination_idx
  on public.destination_keywords(destination_id);
create index if not exists destination_keywords_keyword_idx
  on public.destination_keywords(keyword);
create index if not exists destination_mbti_scores_destination_idx
  on public.destination_mbti_scores(destination_id);
create index if not exists destination_mbti_scores_lookup_idx
  on public.destination_mbti_scores(mbti_type, score desc, destination_id asc);
create index if not exists user_bookmarks_user_id_idx
  on public.user_bookmarks(user_id);
create index if not exists user_bookmarks_destination_id_idx
  on public.user_bookmarks(destination_id);
create index if not exists trips_user_id_idx
  on public.trips(user_id);
create index if not exists trip_plans_user_id_idx
  on public.trip_plans(user_id);
create index if not exists trip_plans_status_idx
  on public.trip_plans(user_id, status, created_at desc);
create index if not exists trip_plan_items_plan_order_idx
  on public.trip_plan_items(plan_id, day_number, order_index);
create index if not exists trip_plan_items_user_id_idx
  on public.trip_plan_items(user_id);
create index if not exists community_posts_user_created_idx
  on public.community_posts(user_id, created_at desc);
create index if not exists community_posts_created_idx
  on public.community_posts(created_at desc);
create index if not exists community_comments_post_idx
  on public.community_comments(post_id, created_at asc);
create index if not exists community_likes_user_idx
  on public.community_likes(user_id);
create index if not exists community_shares_post_idx
  on public.community_shares(post_id);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists user_preferences_set_updated_at on public.user_preferences;
create trigger user_preferences_set_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

drop trigger if exists travel_mbti_results_set_updated_at on public.travel_mbti_results;
create trigger travel_mbti_results_set_updated_at
before update on public.travel_mbti_results
for each row execute function public.set_updated_at();

drop trigger if exists destinations_set_updated_at on public.destinations;
create trigger destinations_set_updated_at
before update on public.destinations
for each row execute function public.set_updated_at();

drop trigger if exists destination_mbti_scores_set_updated_at on public.destination_mbti_scores;
create trigger destination_mbti_scores_set_updated_at
before update on public.destination_mbti_scores
for each row execute function public.set_updated_at();

drop trigger if exists trips_set_updated_at on public.trips;
create trigger trips_set_updated_at
before update on public.trips
for each row execute function public.set_updated_at();

drop trigger if exists trip_plans_set_updated_at on public.trip_plans;
create trigger trip_plans_set_updated_at
before update on public.trip_plans
for each row execute function public.set_updated_at();

drop trigger if exists community_posts_set_updated_at on public.community_posts;
create trigger community_posts_set_updated_at
before update on public.community_posts
for each row execute function public.set_updated_at();

drop trigger if exists community_comments_set_updated_at on public.community_comments;
create trigger community_comments_set_updated_at
before update on public.community_comments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  display_name text;
begin
  display_name := coalesce(
    nullif(new.raw_user_meta_data ->> 'nickname', ''),
    nullif(new.raw_user_meta_data ->> 'name', ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    split_part(coalesce(new.email, 'traveler'), '@', 1),
    'traveler'
  );

  insert into public.users (
    user_id,
    email,
    nickname,
    profile_image,
    profile_completed,
    approved_at
  )
  values (
    new.id,
    coalesce(new.email, ''),
    display_name,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'profile_image', ''),
      nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
      nullif(new.raw_user_meta_data ->> 'picture', '')
    ),
    false,
    now()
  )
  on conflict (user_id) do update
  set
    email = excluded.email,
    nickname = coalesce(public.users.nickname, excluded.nickname),
    profile_image = coalesce(public.users.profile_image, excluded.profile_image),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.refresh_community_post_counts()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_post_id bigint;
begin
  affected_post_id := coalesce(new.post_id, old.post_id);

  update public.community_posts
  set
    like_count = (
      select count(*)::integer
      from public.community_likes
      where community_likes.post_id = affected_post_id
    ),
    comment_count = (
      select count(*)::integer
      from public.community_comments
      where community_comments.post_id = affected_post_id
    ),
    updated_at = now()
  where post_id = affected_post_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists community_likes_refresh_counts on public.community_likes;
create trigger community_likes_refresh_counts
after insert or delete on public.community_likes
for each row execute function public.refresh_community_post_counts();

drop trigger if exists community_comments_refresh_counts on public.community_comments;
create trigger community_comments_refresh_counts
after insert or delete on public.community_comments
for each row execute function public.refresh_community_post_counts();

create or replace view public.community_feed as
select
  p.post_id,
  p.user_id,
  p.title,
  p.summary,
  p.tags,
  p.location,
  p.category,
  p.type,
  p.like_count,
  p.comment_count,
  p.image_urls,
  p.created_at,
  p.updated_at,
  coalesce(u.nickname, p.nickname) as nickname,
  u.profile_image,
  pref.badge,
  pref.mbti_type
from public.community_posts p
left join public.users u
  on u.user_id = p.user_id
left join public.user_preferences pref
  on pref.user_id = p.user_id;

create or replace view public.community_tags_popular as
select
  trim(tag) as tag,
  count(*)::integer as count
from public.community_posts p
cross join lateral regexp_split_to_table(coalesce(p.tags, ''), '\s*,\s*') as tag
where trim(tag) <> ''
group by trim(tag)
order by count(*) desc, tag asc;

alter table public.users enable row level security;
alter table public.user_agreements enable row level security;
alter table public.user_preferences enable row level security;
alter table public.travel_mbti_results enable row level security;
alter table public.destinations enable row level security;
alter table public.destination_keywords enable row level security;
alter table public.destination_mbti_scores enable row level security;
alter table public.user_bookmarks enable row level security;
alter table public.trips enable row level security;
alter table public.trip_plans enable row level security;
alter table public.trip_plan_items enable row level security;
alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_likes enable row level security;
alter table public.community_comment_likes enable row level security;
alter table public.community_shares enable row level security;

grant select on table public.destinations to anon, authenticated;
grant select on table public.destination_keywords to anon, authenticated;
grant select on table public.destination_mbti_scores to anon, authenticated;
grant select on table public.community_feed to authenticated;
grant select on table public.community_tags_popular to authenticated;

grant select, update on table public.users to authenticated;
grant select, insert on table public.user_agreements to authenticated;
grant select, insert, update, delete on table public.user_preferences to authenticated;
grant select, insert, update, delete on table public.travel_mbti_results to authenticated;
grant select, insert, delete on table public.user_bookmarks to authenticated;
grant select, insert, update, delete on table public.trips to authenticated;
grant select, insert, update, delete on table public.trip_plans to authenticated;
grant select, insert, update, delete on table public.trip_plan_items to authenticated;
grant select, insert, update, delete on table public.community_posts to authenticated;
grant select, insert, update, delete on table public.community_comments to authenticated;
grant select, insert, delete on table public.community_likes to authenticated;
grant select, insert, delete on table public.community_comment_likes to authenticated;
grant select, insert, delete on table public.community_shares to authenticated;

grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to authenticated;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists "Authenticated users can view public profiles" on public.users;
create policy "Authenticated users can view public profiles"
on public.users for select
to authenticated
using (true);

drop policy if exists "Users can update their own profile" on public.users;
create policy "Users can update their own profile"
on public.users for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read own agreements" on public.user_agreements;
create policy "Users can read own agreements"
on public.user_agreements for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own agreements" on public.user_agreements;
create policy "Users can insert own agreements"
on public.user_agreements for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can view their own preferences" on public.user_preferences;
create policy "Users can view their own preferences"
on public.user_preferences for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own preferences" on public.user_preferences;
create policy "Users can create their own preferences"
on public.user_preferences for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own preferences" on public.user_preferences;
create policy "Users can update their own preferences"
on public.user_preferences for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own preferences" on public.user_preferences;
create policy "Users can delete their own preferences"
on public.user_preferences for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view own mbti results" on public.travel_mbti_results;
create policy "Users can view own mbti results"
on public.travel_mbti_results for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own mbti results" on public.travel_mbti_results;
create policy "Users can insert own mbti results"
on public.travel_mbti_results for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own mbti results" on public.travel_mbti_results;
create policy "Users can update own mbti results"
on public.travel_mbti_results for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own mbti results" on public.travel_mbti_results;
create policy "Users can delete own mbti results"
on public.travel_mbti_results for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Destinations are publicly readable" on public.destinations;
drop policy if exists "Anyone can read destinations" on public.destinations;
create policy "Destinations are publicly readable"
on public.destinations for select
to anon, authenticated
using (true);

drop policy if exists "Destination keywords are publicly readable" on public.destination_keywords;
create policy "Destination keywords are publicly readable"
on public.destination_keywords for select
to anon, authenticated
using (true);

drop policy if exists "Destination MBTI scores are publicly readable" on public.destination_mbti_scores;
create policy "Destination MBTI scores are publicly readable"
on public.destination_mbti_scores for select
to anon, authenticated
using (true);

drop policy if exists "Users can view own bookmarks" on public.user_bookmarks;
create policy "Users can view own bookmarks"
on public.user_bookmarks for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own bookmarks" on public.user_bookmarks;
create policy "Users can insert own bookmarks"
on public.user_bookmarks for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own bookmarks" on public.user_bookmarks;
create policy "Users can delete own bookmarks"
on public.user_bookmarks for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view their own trips" on public.trips;
create policy "Users can view their own trips"
on public.trips for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own trips" on public.trips;
create policy "Users can create their own trips"
on public.trips for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own trips" on public.trips;
create policy "Users can update their own trips"
on public.trips for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own trips" on public.trips;
create policy "Users can delete their own trips"
on public.trips for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view own trip plans" on public.trip_plans;
create policy "Users can view own trip plans"
on public.trip_plans for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own trip plans" on public.trip_plans;
create policy "Users can insert own trip plans"
on public.trip_plans for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own trip plans" on public.trip_plans;
create policy "Users can update own trip plans"
on public.trip_plans for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own trip plans" on public.trip_plans;
create policy "Users can delete own trip plans"
on public.trip_plans for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view own trip plan items" on public.trip_plan_items;
create policy "Users can view own trip plan items"
on public.trip_plan_items for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own trip plan items" on public.trip_plan_items;
create policy "Users can insert own trip plan items"
on public.trip_plan_items for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.trip_plans
    where trip_plans.plan_id = trip_plan_items.plan_id
      and trip_plans.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can update own trip plan items" on public.trip_plan_items;
create policy "Users can update own trip plan items"
on public.trip_plan_items for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own trip plan items" on public.trip_plan_items;
create policy "Users can delete own trip plan items"
on public.trip_plan_items for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can read community posts" on public.community_posts;
create policy "Authenticated users can read community posts"
on public.community_posts for select
to authenticated
using (true);

drop policy if exists "Users can insert own community posts" on public.community_posts;
create policy "Users can insert own community posts"
on public.community_posts for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own community posts" on public.community_posts;
create policy "Users can update own community posts"
on public.community_posts for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own community posts" on public.community_posts;
create policy "Users can delete own community posts"
on public.community_posts for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can read community comments" on public.community_comments;
create policy "Authenticated users can read community comments"
on public.community_comments for select
to authenticated
using (true);

drop policy if exists "Users can insert own community comments" on public.community_comments;
create policy "Users can insert own community comments"
on public.community_comments for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own community comments" on public.community_comments;
create policy "Users can update own community comments"
on public.community_comments for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own community comments" on public.community_comments;
create policy "Users can delete own community comments"
on public.community_comments for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can read community likes" on public.community_likes;
create policy "Authenticated users can read community likes"
on public.community_likes for select
to authenticated
using (true);

drop policy if exists "Users can insert own community likes" on public.community_likes;
create policy "Users can insert own community likes"
on public.community_likes for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own community likes" on public.community_likes;
create policy "Users can delete own community likes"
on public.community_likes for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can read comment likes" on public.community_comment_likes;
create policy "Authenticated users can read comment likes"
on public.community_comment_likes for select
to authenticated
using (true);

drop policy if exists "Users can insert own comment likes" on public.community_comment_likes;
create policy "Users can insert own comment likes"
on public.community_comment_likes for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own comment likes" on public.community_comment_likes;
create policy "Users can delete own comment likes"
on public.community_comment_likes for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can read community shares" on public.community_shares;
create policy "Authenticated users can read community shares"
on public.community_shares for select
to authenticated
using (true);

drop policy if exists "Users can insert own community shares" on public.community_shares;
create policy "Users can insert own community shares"
on public.community_shares for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own community shares" on public.community_shares;
create policy "Users can delete own community shares"
on public.community_shares for delete
to authenticated
using ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('community-images', 'community-images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Avatar images are publicly readable" on storage.objects;
create policy "Avatar images are publicly readable"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'avatars');

drop policy if exists "Users can upload avatars" on storage.objects;
create policy "Users can upload avatars"
on storage.objects for insert
to authenticated
with check (bucket_id = 'avatars' and owner = (select auth.uid()));

drop policy if exists "Users can update own avatars" on storage.objects;
create policy "Users can update own avatars"
on storage.objects for update
to authenticated
using (bucket_id = 'avatars' and owner = (select auth.uid()))
with check (bucket_id = 'avatars' and owner = (select auth.uid()));

drop policy if exists "Users can delete own avatars" on storage.objects;
create policy "Users can delete own avatars"
on storage.objects for delete
to authenticated
using (bucket_id = 'avatars' and owner = (select auth.uid()));

drop policy if exists "Community images are publicly readable" on storage.objects;
create policy "Community images are publicly readable"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'community-images');

drop policy if exists "Users can upload community images" on storage.objects;
create policy "Users can upload community images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'community-images' and owner = (select auth.uid()));

drop policy if exists "Users can update own community images" on storage.objects;
create policy "Users can update own community images"
on storage.objects for update
to authenticated
using (bucket_id = 'community-images' and owner = (select auth.uid()))
with check (bucket_id = 'community-images' and owner = (select auth.uid()));

drop policy if exists "Users can delete own community images" on storage.objects;
create policy "Users can delete own community images"
on storage.objects for delete
to authenticated
using (bucket_id = 'community-images' and owner = (select auth.uid()));

comment on table public.trip_plans is
  '현재 일정 확인 API의 기준 테이블. trips와 병행 사용 중인 과도기 구조.';
comment on table public.trip_plan_items is
  'trip_plans의 DAY별 관광지 항목.';
comment on column public.users.profile_completed is
  '소셜 로그인 사용자의 최초 프로필 설정 완료 여부.';

commit;
