begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email varchar(255) unique not null,
  nickname varchar(100) not null,
  profile_image varchar(500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_preferences (
  preference_id bigint generated by default as identity primary key,
  user_id uuid unique not null references public.users(user_id) on delete cascade,
  travel_tempo varchar(100),
  food_preference varchar(100),
  badge varchar(100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.destinations (
  destination_id bigint generated by default as identity primary key,
  province varchar(100) not null,
  city varchar(100),
  destination_name varchar(255) not null,
  description text,
  category varchar(100),
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  image_url varchar(500),
  average_budget integer,
  created_at timestamptz not null default now(),
  constraint destinations_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint destinations_longitude_check
    check (longitude is null or longitude between -180 and 180),
  constraint destinations_average_budget_check
    check (average_budget is null or average_budget >= 0)
);

create table public.trips (
  trip_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  destination_id bigint not null references public.destinations(destination_id) on delete restrict,
  title varchar(255) not null,
  start_date date,
  end_date date,
  budget integer,
  companion_type varchar(50),
  status varchar(50) not null default 'planning',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trips_date_range_check
    check (start_date is null or end_date is null or end_date >= start_date),
  constraint trips_budget_check
    check (budget is null or budget >= 0),
  constraint trips_status_check
    check (status in ('planning', 'in_progress', 'completed', 'cancelled'))
);

create table public.itineraries (
  itinerary_id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(trip_id) on delete cascade,
  day_number integer not null,
  start_time time,
  location_name varchar(255) not null,
  description text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  sort_order integer not null default 0,
  constraint itineraries_day_number_check
    check (day_number >= 1),
  constraint itineraries_sort_order_check
    check (sort_order >= 0),
  constraint itineraries_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint itineraries_longitude_check
    check (longitude is null or longitude between -180 and 180)
);

create index user_preferences_user_id_idx
  on public.user_preferences(user_id);
create index destinations_region_idx
  on public.destinations(province, city);
create index destinations_category_idx
  on public.destinations(category);
create index trips_user_id_idx
  on public.trips(user_id);
create index trips_destination_id_idx
  on public.trips(destination_id);
create index trips_start_date_idx
  on public.trips(start_date);
create index itineraries_trip_order_idx
  on public.itineraries(trip_id, day_number, sort_order);

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger user_preferences_set_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

create trigger trips_set_updated_at
before update on public.trips
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.users (user_id, email, nickname, profile_image)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'nickname', split_part(coalesce(new.email, 'traveler'), '@', 1)),
    new.raw_user_meta_data ->> 'profile_image'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

alter table public.users enable row level security;
alter table public.user_preferences enable row level security;
alter table public.destinations enable row level security;
alter table public.trips enable row level security;
alter table public.itineraries enable row level security;

grant select on table public.destinations to anon, authenticated;
grant select, update on table public.users to authenticated;
grant select, insert, update, delete on table public.user_preferences to authenticated;
grant select, insert, update, delete on table public.trips to authenticated;
grant select, insert, update, delete on table public.itineraries to authenticated;

grant usage, select on sequence public.user_preferences_preference_id_seq to authenticated;
grant usage, select on sequence public.trips_trip_id_seq to authenticated;
grant usage, select on sequence public.itineraries_itinerary_id_seq to authenticated;

grant all on table public.users to service_role;
grant all on table public.user_preferences to service_role;
grant all on table public.destinations to service_role;
grant all on table public.trips to service_role;
grant all on table public.itineraries to service_role;
grant usage, select on sequence public.user_preferences_preference_id_seq to service_role;
grant usage, select on sequence public.destinations_destination_id_seq to service_role;
grant usage, select on sequence public.trips_trip_id_seq to service_role;
grant usage, select on sequence public.itineraries_itinerary_id_seq to service_role;

create policy "Users can view their own profile"
on public.users
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can update their own profile"
on public.users
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can view their own preferences"
on public.user_preferences
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own preferences"
on public.user_preferences
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own preferences"
on public.user_preferences
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own preferences"
on public.user_preferences
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Destinations are publicly readable"
on public.destinations
for select
to anon, authenticated
using (true);

create policy "Users can view their own trips"
on public.trips
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own trips"
on public.trips
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own trips"
on public.trips
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own trips"
on public.trips
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can view itineraries for their trips"
on public.itineraries
for select
to authenticated
using (
  exists (
    select 1
    from public.trips
    where trips.trip_id = itineraries.trip_id
      and trips.user_id = (select auth.uid())
  )
);

create policy "Users can create itineraries for their trips"
on public.itineraries
for insert
to authenticated
with check (
  exists (
    select 1
    from public.trips
    where trips.trip_id = itineraries.trip_id
      and trips.user_id = (select auth.uid())
  )
);

create policy "Users can update itineraries for their trips"
on public.itineraries
for update
to authenticated
using (
  exists (
    select 1
    from public.trips
    where trips.trip_id = itineraries.trip_id
      and trips.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.trips
    where trips.trip_id = itineraries.trip_id
      and trips.user_id = (select auth.uid())
  )
);

create policy "Users can delete itineraries for their trips"
on public.itineraries
for delete
to authenticated
using (
  exists (
    select 1
    from public.trips
    where trips.trip_id = itineraries.trip_id
      and trips.user_id = (select auth.uid())
  )
);

commit;
