begin;

alter table public.user_preferences
  add column if not exists mbti_type varchar(4);

alter table public.user_preferences
  drop constraint if exists user_preferences_mbti_type_check;

alter table public.user_preferences
  add constraint user_preferences_mbti_type_check
  check (
    mbti_type is null or mbti_type in (
      'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
      'ISTP', 'ISFP', 'INFP', 'INTP',
      'ESTP', 'ESFP', 'ENFP', 'ENTP',
      'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ'
    )
  );

alter table public.destinations
  add column if not exists tour_content_id varchar(50),
  add column if not exists content_type_id integer,
  add column if not exists address varchar(500),
  add column if not exists category_code1 varchar(20),
  add column if not exists category_code2 varchar(20),
  add column if not exists category_code3 varchar(20),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists destinations_tour_content_id_idx
  on public.destinations(tour_content_id)
  where tour_content_id is not null;

create table if not exists public.destination_keywords (
  destination_keyword_id bigint generated by default as identity primary key,
  destination_id bigint not null
    references public.destinations(destination_id) on delete cascade,
  keyword varchar(50) not null,
  source varchar(20) not null default 'RULE',
  confidence numeric(4, 3) not null default 1,
  rule_version varchar(50),
  created_at timestamptz not null default now(),
  constraint destination_keywords_unique unique (destination_id, keyword),
  constraint destination_keywords_source_check
    check (source in ('TOUR_API', 'RULE', 'AI', 'ADMIN')),
  constraint destination_keywords_confidence_check
    check (confidence between 0 and 1)
);

create table if not exists public.destination_mbti_scores (
  destination_mbti_score_id bigint generated by default as identity primary key,
  destination_id bigint not null
    references public.destinations(destination_id) on delete cascade,
  mbti_type varchar(4) not null,
  score numeric(5, 2) not null,
  reason text,
  source varchar(20) not null default 'RULE',
  rule_version varchar(50) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint destination_mbti_scores_unique
    unique (destination_id, mbti_type),
  constraint destination_mbti_scores_mbti_type_check
    check (
      mbti_type in (
        'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
        'ISTP', 'ISFP', 'INFP', 'INTP',
        'ESTP', 'ESFP', 'ENFP', 'ENTP',
        'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ'
      )
    ),
  constraint destination_mbti_scores_score_check
    check (score between 0 and 100),
  constraint destination_mbti_scores_source_check
    check (source in ('RULE', 'AI', 'ADMIN'))
);

create index if not exists destination_keywords_destination_idx
  on public.destination_keywords(destination_id);
create index if not exists destination_keywords_keyword_idx
  on public.destination_keywords(keyword);
create index if not exists destination_mbti_scores_destination_idx
  on public.destination_mbti_scores(destination_id);
create index if not exists destination_mbti_scores_lookup_idx
  on public.destination_mbti_scores(mbti_type, score desc);

drop trigger if exists destinations_set_updated_at on public.destinations;
create trigger destinations_set_updated_at
before update on public.destinations
for each row execute function public.set_updated_at();

drop trigger if exists destination_mbti_scores_set_updated_at
  on public.destination_mbti_scores;
create trigger destination_mbti_scores_set_updated_at
before update on public.destination_mbti_scores
for each row execute function public.set_updated_at();

alter table public.destination_keywords enable row level security;
alter table public.destination_mbti_scores enable row level security;

grant select on table public.destination_keywords to anon, authenticated;
grant select on table public.destination_mbti_scores to anon, authenticated;
grant all on table public.destination_keywords to service_role;
grant all on table public.destination_mbti_scores to service_role;
grant usage, select on sequence
  public.destination_keywords_destination_keyword_id_seq to service_role;
grant usage, select on sequence
  public.destination_mbti_scores_destination_mbti_score_id_seq to service_role;

drop policy if exists "Destination keywords are publicly readable"
  on public.destination_keywords;
create policy "Destination keywords are publicly readable"
on public.destination_keywords
for select
to anon, authenticated
using (true);

drop policy if exists "Destination MBTI scores are publicly readable"
  on public.destination_mbti_scores;
create policy "Destination MBTI scores are publicly readable"
on public.destination_mbti_scores
for select
to anon, authenticated
using (true);

commit;
